config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end
    unauthenticated do
      root 'splash#index',  as: :unauthenticated_root
    end
  end
  resources :categories, only: [:index, :new, :create] do
    resources :transactions, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions

  has_one_attached :image

  validates :name, presence: true, length: { maximum: 250 }

  def total_transactions_amount
    total = 0
    transactions.each do |transaction|
      total += transaction.amount
    end
    total
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, presence: true, numericality: { greater_than: 0, less_than: 999_999_999 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :transactions, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action :configured_permitted_parameters, if: :devise_controller?

  private

  def configured_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :password)
    end
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(cate_params)
    if @category.save
      flash[:notice] = 'Category has been created'
      redirect_to categories_path
    else
      flash[:notice] = 'Invalid Category'
    end
  end

  private

  def cate_params
    params.require(:category).permit(:name, :image)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @category = current_user.categories.find(params[:category_id])
  end

  def new
    @category = Category.find(params[:category_id])
    @transaction = Transaction.new
  end

  def create
    @category = Category.find(params[:category_id])
    @transaction = @category.transactions.new(name: trans_params[:name],
                                              amount: trans_params[:amount], user_id: current_user.id)
    if @transaction.save
      flash[:notice] = 'Transaction is completed'
      redirect_to category_transactions_path(@category)
    else
      flash[:notice] = 'Invalid Transaction!'
    end
  end

  private

  def trans_params
    params.require(:transaction).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_category_form.html.erb
<%= render partial: 'shared/navbar', locals: { heading: 'CREATE CATEGORIES', back_path: categories_path } %>

<%= form_for :category, url: categories_path, method: :post do |form|  %>
  <div class='category_form'>
    <%= form.text_field :name, class: 'category_form_field category_name_field', placeholder: 'Category Name' %>
    Insert icon  <%= form.file_field :image %>
    <%= form.submit "Submit", class: 'category_form_field category_form_btn' %>
  </div>
<% end %>

app/views/categories/index.html.erb
<%= render partial: 'shared/navbar', locals: { heading: 'CATEGORIES', back_path: categories_path } %>
<ul class="categories_directory">
<% @categories.includes(:transactions).each do |cate| %>
  <li class="categories_container_padding">
    <ul class="categories_container">
      <li class="category_img">
        <%= image_tag(cate.image, class:"category_img") if cate.image.attached? %>
      </li>
      <li class="category-detail-container">
        <span><%= link_to cate.name, category_transactions_path(category_id: cate.id) %></span>
        <span><%= cate.created_at.strftime("%d-%m-%Y") %></span>
      </li>
      <li class="category_amount_container">
        <span>$<%= cate.total_transactions_amount %></span>
      </li>
    </ul>
  </li>
<% end %>
</ul>
<div class: 'create_category_btn_container'>
  <%= link_to "Create Category", new_category_path, class: 'create_category_btn' %>
</div>

app/views/categories/new.html.erb
<%= render partial: 'category_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <%= link_to image_tag("back-icon.png"), back_path, class: 'back-btn' %>
  <h3 class="nav_heading"><%= heading %></h3>
  <%if user_signed_in?%>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'sign_out_btn' %>
  <% else %>
    <%= link_to "", class: "empty"  %>
  <% end %>
</nav>

app/views/splash/index.html.erb
<h1 class='splash_screen_heading'>MyBudget<h1>

<div class='splash_page_btns'>
  <%= link_to 'Login', new_user_session_path, class: 'splash_btn splash_login_btn' %>
  <%= link_to 'Sign up', new_user_registration_path, class: 'splash_btn splash_reg_btn' %>
</div>

app/views/transactions/_transaction_form.html.erb
<%= form_for :transaction, url: category_transactions_path(@category), method: :post do |form|  %>
  <div class='transaction-form'>
    <%= form.text_field :name, class: 'transaction_name_field transaction_form_field', placeholder: 'Name' %>
    <%= form.text_field :amount, class: 'transaction_amount_field transaction_form_field', placeholder: 'Amount' %>
    <%= form.submit "Submit", class: 'transaction_form_btn transaction_form_field' %>
  </div>
<% end %>

app/views/transactions/index.html.erb
<%= render partial: 'shared/navbar', locals: { heading: 'TRANSACTIONS', back_path: categories_path } %>
<ul class='transactions-container-padding'>
<% @category.transactions.each do |transaction| %>
  <li class='transactions-container'>
    <span><%= transaction.name %></span>
    <span>$<%= transaction.amount %></span>
  </li>
<% end %>
</ul>
<%= link_to "Create Transaction", new_category_transaction_path(@category), class: 'transaction-create-btn' %>

app/views/transactions/new.html.erb
<%= render partial: 'shared/navbar', locals: { heading: 'CREATE TRANSACTION', back_path: category_transactions_path(@category) } %>
<%= render partial: 'transaction_form' %>